baseurl: http://jebaird.com
exclude: ["README.md", "LICENSE.md", "TODO.md", "build", "test","_drafts"]

safe: true

markdown: rdiscount

owner_name: "Jesse Baird"
owner_page: "jebaird.com"
owner_mail: "jebaird@gmail.com"

title: "jebaird.com"
slogan: "the personal bog of Jesse Baird"
url: "/"

paginate: 7